name: joy
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  image_picker: ^1.0.2
  background_app_bar: ^2.0.1
  intl: ^0.18.0
  calendar_date_picker2: ^0.5.3
  fluttertoast: ^8.2.2
  video_player: ^2.7.0
  page_view_dot_indicator: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: fonts/Pretendard-Light.ttf
          weight: 300
        - asset: fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: fonts/Pretendard-Black.ttf
          weight: 900