// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-go_T0y0uCmSM332U_KBE4uKkIPm1qRw',
    appId: '1:11255186132:web:687ac2016968f3aeed7141',
    messagingSenderId: '11255186132',
    projectId: 'joinus-76564',
    authDomain: 'joinus-76564.firebaseapp.com',
    storageBucket: 'joinus-76564.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6i_BBwlBZD5sgBAsJ6-5LCF7gHWNC3M',
    appId: '1:11255186132:android:c6d3cf60075cbf0ced7141',
    messagingSenderId: '11255186132',
    projectId: 'joinus-76564',
    storageBucket: 'joinus-76564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOZ1I9vrzFU_5r2nCoe7ujd_rVCfa3q1k',
    appId: '1:11255186132:ios:c385671e0a37f9daed7141',
    messagingSenderId: '11255186132',
    projectId: 'joinus-76564',
    storageBucket: 'joinus-76564.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOZ1I9vrzFU_5r2nCoe7ujd_rVCfa3q1k',
    appId: '1:11255186132:ios:c385671e0a37f9daed7141',
    messagingSenderId: '11255186132',
    projectId: 'joinus-76564',
    storageBucket: 'joinus-76564.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-go_T0y0uCmSM332U_KBE4uKkIPm1qRw',
    appId: '1:11255186132:web:fe3a8ca399c3fdfeed7141',
    messagingSenderId: '11255186132',
    projectId: 'joinus-76564',
    authDomain: 'joinus-76564.firebaseapp.com',
    storageBucket: 'joinus-76564.appspot.com',
  );

}